making dblogger's tests pass, although it appears that pytest-capturelog is doing something wrong that causes a huge series of these tracebacks:
ValueError: I/O operation on closed file
Logged from file test_dblogger_throughput.py, line 76
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 867, in emit
    stream.write(fs % msg)
  File "/home/jrf/ve-dev/local/lib/python2.7/site-packages/_pytest/capture.py", line 34, in write
    StringIO.write(self, data)
ValueError: I/O operation on closed file
Logged from file test_dblogger_throughput.py, line 76
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 867, in emit
    stream.write(fs % msg)
  File "/home/jrf/ve-dev/local/lib/python2.7/site-packages/_pytest/capture.py", line 34, in write
    StringIO.write(self, data)
ValueError: I/O operation on closed file
Logged from file test_dblogger_throughput.py, line 76
PASSED

========================== 14 passed in 2.45 seconds ===========================
[4]   Done                    py.test dblogger -vvs --runperf --redis-address "redis.diffeo.com:6379" &>f